### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError

### ISSUE THREAD

**Issue by Jackson-en** [fmolivato/cwtLayerKeras#3] opened 2021-07-23 12:22 UTC
tensorflow.python.framework.errors_impl.FailedPreconditionError: Could not find variable cwt_layer/Variable. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/cwt_layer/Variable/class tensorflow::Var does not exist.
	 [[{{node cwt_layer/loop_body_2/Reshape/ReadVariableOp}}]]

what？

**Comment by fmolivato** [comment] 2021-07-23 13:46
It seems that you have some problems with the inner loop, wich is the actual convolution process of the signal with the scaled wavelet.
However it's hard to understand the problem just form that error, so I need more info:
- os
- tf version
- the code (the entire text, or just the function that contain the actual call to the layer).

**Comment by Jackson-en** [comment] 2021-07-26 01:16
windows 11
tensorflow-cpu-2.5.0

```python
def build_model():
    input_data = layers.Input(shape=(18,14,1,))
    input1 = K.reshape(input_data,(-1,1))
    cwt = cwtt(
        sample_count=1,
        scales_step=10,
        min_scale=4,
        max_scale=18,
        output_size=(18, 14),
        depth_pad=0,
    )
    scalogram = cwt(input1)
    # scalogram1 = K.reshape(scalogram,(-1,18,14,1))
    # base_model = EfficientNetB0(include_top=None,weights=None)(scalogram)

    # x = layers.GlobalAveragePooling2D()(scalogram)
    x1 = layers.BatchNormalization()(scalogram)
    x2 = layers.Flatten()(x1)
    x3 = layers.Dropout(0.3)(x2)
    predictions = layers.Dense(4, activation="softmax")(x3)
    model = Model(inputs=input_data, outputs=predictions)

    model.summary()
    model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
    return model

model = build_model()
model.fit(trainx, trainy, epochs=1, batch_size=16, validation_data=(valx, valy))
```

There is no problem with creating models, there is a problem with FIT

**Comment by fmolivato** [comment] 2021-07-26 08:47
I advise you to read the layer docs in the source code.

A single Raman spectrum should be a 1dimensional array (i used np-array), which is a sequence of Raman shifts values.
My train set is just a tensor of N stacked spectra, so the size should be like this:
[train_size, **signal_length**]

The *input_data* shape needs to be equal to **signal_length**, as you can see in the README example. 
The *sample_count* value needs to be the same as the input_data's shape because *sample_count* is just the amount of Raman shifts in the spectra.

That said, I suggest building the train set as I told you earlier, and then change the input_data shape as *trainx.shape[-1]* as well as the sample count.
After these fixes, your code should be like the one below.

Let's suppose you have 32 spectra and that a single spectrum has 10 Raman shifts.
Then your **trainx** shape should be [32, 10], and the code becomes:

```python
def build_model():
    input_data = layers.Input(shape=(trainx.shape[-1],))
    #input1 = K.reshape(input_data,(-1,1)) **REMOVED**
    cwt = cwtt(
        sample_count=trainx.shape[-1],
        scales_step=10,
        min_scale=4,
        max_scale=18,
        output_size=(18, 14),
        depth_pad=0,
    )
    scalogram = cwt(input1)

    x1 = layers.BatchNormalization()(scalogram)
    x2 = layers.Flatten()(x1)
    x3 = layers.Dropout(0.3)(x2)
    predictions = layers.Dense(4, activation="softmax")(x3)
    model = Model(inputs=input_data, outputs=predictions)

    model.summary()
    model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
    return model

model = build_model()
model.fit(trainx, trainy, epochs=1, batch_size=16, validation_data=(valx, valy))
```

I'm not able to test it myself for a couple of weeks so let me know how it goes

**Comment by Jackson-en** [comment] 2021-07-26 09:38
> I advise you to read the layer docs in the source code.
> 
> A single Raman spectrum should be a 1dimensional array (i used np-array), which is a sequence of Raman shifts values.
> My train set is just a tensor of N stacked spectra, so the size should be like this:
> [train_size, **signal_length**]
> 
> The _input_data_ shape needs to be equal to **signal_length**, as you can see in the README example.
> The _sample_count_ value needs to be the same as the input_data's shape because _sample_count_ is just the amount of Raman shifts in the spectra.
> 
> That said, I suggest building the train set as I told you earlier, and then change the input_data shape as _trainx.shape[-1]_ as well as the sample count.
> After these fixes, your code should be like the one below.
> 
> Let's suppose you have 32 spectra and that a single spectrum has 10 Raman shifts.
> Then your **trainx** shape should be [32, 10], and the code becomes:
> 
> ```python
> def build_model():
>     input_data = layers.Input(shape=(trainx.shape[-1],))
>     #input1 = K.reshape(input_data,(-1,1)) **REMOVED**
>     cwt = cwtt(
>         sample_count=trainx.shape[-1],
>         scales_step=10,
>         min_scale=4,
>         max_scale=18,
>         output_size=(18, 14),
>         depth_pad=0,
>     )
>     scalogram = cwt(input1)
> 
>     x1 = layers.BatchNormalization()(scalogram)
>     x2 = layers.Flatten()(x1)
>     x3 = layers.Dropout(0.3)(x2)
>     predictions = layers.Dense(4, activation="softmax")(x3)
>     model = Model(inputs=input_data, outputs=predictions)
> 
>     model.summary()
>     model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
>     return model
> 
> model = build_model()
> model.fit(trainx, trainy, epochs=1, batch_size=16, validation_data=(valx, valy))
> ```
> 
> I'm not able to test it myself for a couple of weeks so let me know how it goes

**Comment by Jackson-en** [comment] 2021-07-26 09:39
> > I advise you to read the layer docs in the source code.
> > A single Raman spectrum should be a 1dimensional array (i used np-array), which is a sequence of Raman shifts values.
> > My train set is just a tensor of N stacked spectra, so the size should be like this:
> > [train_size, **signal_length**]
> > The _input_data_ shape needs to be equal to **signal_length**, as you can see in the README example.
> > The _sample_count_ value needs to be the same as the input_data's shape because _sample_count_ is just the amount of Raman shifts in the spectra.
> > That said, I suggest building the train set as I told you earlier, and then change the input_data shape as _trainx.shape[-1]_ as well as the sample count.
> > After these fixes, your code should be like the one below.
> > Let's suppose you have 32 spectra and that a single spectrum has 10 Raman shifts.
> > Then your **trainx** shape should be [32, 10], and the code becomes:
> > ```python
> > def build_model():
> >     input_data = layers.Input(shape=(trainx.shape[-1],))
> >     #input1 = K.reshape(input_data,(-1,1)) **REMOVED**
> >     cwt = cwtt(
> >         sample_count=trainx.shape[-1],
> >         scales_step=10,
> >         min_scale=4,
> >         max_scale=18,
> >         output_size=(18, 14),
> >         depth_pad=0,
> >     )
> >     scalogram = cwt(input1)
> > 
> >     x1 = layers.BatchNormalization()(scalogram)
> >     x2 = layers.Flatten()(x1)
> >     x3 = layers.Dropout(0.3)(x2)
> >     predictions = layers.Dense(4, activation="softmax")(x3)
> >     model = Model(inputs=input_data, outputs=predictions)
> > 
> >     model.summary()
> >     model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
> >     return model
> > 
> > model = build_model()
> > model.fit(trainx, trainy, epochs=1, batch_size=16, validation_data=(valx, valy))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not able to test it myself for a couple of weeks so let me know how it goes

OK

**Comment by fmolivato** [comment] 2021-08-08 06:22
i assume that the problem is solved so i'm closing the issue

**Closed as completed by fmolivato** 2021-08-08 06:22 UTC
Labels: bug
